version: "3.9"
services:
  passbolt-mariadb:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt-mariadb-internal"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt-server:
    image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - passbolt-mariadb
    environment:
      APP_FULL_BASE_URL: https://secrets.domain.com
      DATASOURCES_DEFAULT_HOST: "passbolt-mariadb"
      DATASOURCES_DEFAULT_DATABASE: "passbolt-mariadb-internal"
      DATASOURCES_DEFAULT_USERNAME: "username"
      DATASOURCES_DEFAULT_PASSWORD: "password"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passbolt-mariadb:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      traefik.enable: "true"
      traefik.http.routers.passbolt-http.entrypoints: "web"
      traefik.http.routers.passbolt-http.rule: "Host(`secrets.domain.com`)"
      traefik.http.routers.passbolt-http.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.entrypoints: "websecure"
      traefik.http.routers.passbolt-https.rule: "Host(`secrets.domain.com`)"
      traefik.http.routers.passbolt-https.tls: "true"
      traefik.http.routers.passbolt-https.tls.certresolver: "letsencrypt"
      traefik.http.services.passbolt-https.loadbalancer.server.port: 8080

  yopass-memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass-server:
    image: jhaals/yopass
    restart: always
    command: "--memcached=yopass-memcached:11211"
    labels:
      traefik.enable: "true"
      traefik.http.routers.yopass-http.entrypoints: "web"
      traefik.http.routers.yopass-http.rule: "Host(`ots.domain.com`)"
      traefik.http.routers.yopass-http.middlewares: "SslHeader@file"
      traefik.http.routers.yopass-https.middlewares: "SslHeader@file"
      traefik.http.routers.yopass-https.entrypoints: "websecure"
      traefik.http.routers.yopass-https.rule: "Host(`ots.domain.com`)"
      traefik.http.routers.yopass-https.tls: "true"
      traefik.http.routers.yopass-https.tls.certresolver: "letsencrypt"
      traefik.http.services.yopass-https.loadbalancer.server.port: 1337

  traefik:
    image: traefik:2.9.8
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./conf/:/etc/traefik/conf
      - ./shared/:/shared

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

